### ISSUE TITLE
reloading properties results in the docker infrastructure location disappearing

### ISSUE THREAD

**Issue by johnmccabe** [brooklyncentral/clocker#290]
Have only observed this behaviour in relation to a docker infrastructure location so raising here, issue may belong on the brooklyn project.

A healthy running docker instracture results in a `my-docker-cloud` location in the catalog, hitting `reload properties` on the console results in a rescan of the properties file with any locations defined there being repopulated but the docker location disappearing.

The location does not reappear (waited 10 minutes).

**Comment by aledsage** [comment]
See the changes made for https://github.com/brooklyncentral/clocker/issues/237

We no longer call `DockerUtils.reloadLocationListener()` in `createLocation()` or `rebind()`, which would register the reload listener. That approach broke rebind, but unfortunately removing it means we don't properly support "reload brooklyn properties".

I see a couple of possible fixes:

1. we could register a reload brooklyn properties listener again (in the location code).

2. or we could add the location to the catalog instead of directly to the location registry.

**Comment by johnmccabe** [comment]
@aledsage / @grkvlt this is still happening for me, built clocker from master (https://github.com/brooklyncentral/clocker/commit/6f93a9b2dc9fb2fe801227afe88a7d13fbaeb7e8), deployed a docker infra, hit reload and the docker infra location is gone.

**Comment by johnmccabe** [comment]
scratch that, seems to be working ok, location survived rebind and reload.. if it occurs again I'll open a new ticket.
